# Generated by Django 5.1.6 on 2025-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
