# Generated by Django 5.1.6 on 2025-02-23 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_package_inventory_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
