# Generated by Django 5.1.6 on 2025-02-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='category',
            new_name='categories',
        ),
    ]
